# Generated by Django 5.0 on 2023-12-11 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polar_bear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonyme', max_length=42)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polar_bear.article')),
            ],
        ),
    ]
